name: leben_in_deutschland
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #State Management
  provider: ^6.1.2

  #firebase
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  
  #DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Functionality
  flutter_email_sender: ^6.0.3
  url_launcher: ^6.2.6
  auto_size_text: ^3.0.0
  translator: ^1.0.0
  flutter_cached_pdfview: ^0.4.2
  path_provider: ^2.1.3
  feedback: ^3.1.0
  rate_my_app: ^2.1.0
  flutter_dotenv: ^5.1.0
  user_messaging_platform: ^1.3.0

  #UI
  dotted_line: ^3.2.2
  slide_countdown: ^1.6.1
  pie_chart: ^5.4.0

  #Animations
  rive: ^0.13.4

  #Ads
  google_mobile_ads: ^5.1.0

dependency_overrides:
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/app_logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/app_logo.png"
  adaptive_icon_background: "#ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/jsons/lid_fragen.json
    - assets/pdfs/GG.pdf
    - assets/jsons/stateQuestions/
    - assets/images/
    - assets/animations/
    - assets/logos/
    - .env
